# Generated by Django 4.1.2 on 2022-10-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('nid', models.CharField(max_length=150)),
                ('company_operator', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlansModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=250)),
                ('per_month_pay_bd_taka', models.IntegerField()),
                ('durability', models.IntegerField()),
                ('dial_number', models.CharField(max_length=250)),
                ('plan_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanCustomerBuyPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_month_pay_bd_amount', models.IntegerField()),
                ('plan_active', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('offer_activation_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicaltestapp.customer')),
                ('plans_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicaltestapp.plansmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OfferNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dial_number', models.CharField(max_length=250)),
                ('plan_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicaltestapp.plansmodel')),
            ],
        ),
    ]
