# Generated by Django 4.1.2 on 2022-10-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicaltestapp', '0002_alter_customer_company_operator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferNumber',
        ),
    ]
